### ISSUE TITLE
jenkin unable to recognize platform repo

### ISSUE THREAD

**Issue by tariqinaam** [millerrs/jenkins-pipeline-platformsh#1]
Hi,
I am trying to integrate jenkins with platform sh. however when creating pipeline, i get following error:
Field: scmConfig.name
Code: INVALID
Message: project_id@git in not a valid name

did you experience any similar issue with the integration.
I have added jenkins public ssh key into platform.sh key list.

**Comment by millerrs** [comment]
The git URL doesn't look correct.  It should look like <project_id>@git.us.platform.sh:<project_id>.git

**Comment by tariqinaam** [comment]
thats exactly what i have in git url field. see [image](http://tinyurl.com/yxszy4cq)

**Comment by millerrs** [comment]
That’s interesting. I tried the same thing and got the same error. If you haven’t already, I would ask your question on Platform.sh’s [slack channel](https://chat.platform.sh/). Someone on there know why it’s not working although I wouldn’t be surprised if it’s a Jenkins issue. For projects I’ve been involved in, I haven’t used Platform.sh’s git for Blue Ocean. Rather, I use GitHub or Bitbucket and setup an [integration](https://docs.platform.sh/administration/integrations.html) with Platform.sh.
